name: Prettier Code Style Check

on:
  push:
    branches:
      - main

jobs:
  prettier-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Action to check out your repository code

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your desired Node.js version (e.g., '18', '22')
          cache: 'npm' # Cache npm dependencies for faster builds (or 'yarn' if you use yarn)

      - name: Install Dependencies
        run: npm install # Install project dependencies, including Prettier

      - name: Run Prettier Check
        run: npm run check-format # Assumes you have 'check-format' script in package.json
        # If you don't have this script, use: run: npx prettier --check .
        # The '--check' flag ensures it only checks and exits with a non-zero code if issues are found.

      - name: Verify No Uncommitted Changes (Optional, for stricter checks)
        # This step ensures that 'npm run check-format' didn't leave any changes
        # which might indicate a misconfiguration or a formatter that also writes.
        run: |
          git diff --exit-code
